In [1]:
#自作クラスのインポート
from packages import Exam

# 必要モジュールのインポート
import os
import numpy as np
import pandas as pd
from glob import glob

In [2]:
#環境変数の設定
BasePath = fr".\files"

In [3]:
#ファイル名の変更
for i, filepath in enumerate(sorted(glob(f"{BasePath}/scan/*.jpg"))):
    print(os.path.basename(filepath))
    os.path.dirname(filepath)
    os.rename(filepath, F"{os.path.dirname(filepath)}/{str(i+1).zfill(2)}.jpg")

01.jpg
02.jpg
03.jpg


スキャン結果から出席番号の読み取り

In [4]:
sheets = []

if os.path.exists(f"{BasePath}/concat"):

    print("Loading")
    #スキャンデータを結合，方向補正，出席番号を取得して保存
    tergetfolder = "concat"
    for i, filepath in enumerate(glob(f"{BasePath}/{tergetfolder}/*")):
        print(os.path.basename(filepath))
        sheets.append(Exam.Paper(BasePath))
        student_num = int(os.path.splitext(os.path.basename(filepath))[0])
        sheets[i].readsheet(tergetfolder, student_num)
        sheets[i].show("concat", 1)

else:

    print("Concat Sheets...")
    for i, filepath in enumerate(sorted(glob(f"{BasePath}/scan/*.jpg"))):
        print(os.path.basename(filepath))
        sheets.append(Exam.Paper(BasePath))
        num = int((i-1)/2)
        sheets[num].makesheet(filepath)
        sheets[num].show("concat", 1)
        sheets[num].get_student(startpoints = (0.14, 0.08), endpoints = (0.29, 0.17))
        sheets[num].save("concat")
        sheets[num].save("check")
        
    sheets = sorted(sheets, key=lambda s: s.student_num)

Loading
01.jpg
02.jpg
03.jpg


問題の定義（配点と正答の設定）

In [5]:
#問題を定義
questions = []

#インデックス0はダミーで埋める
questions.append(Exam.Question(sheets, "dummy", [(0, 0), (1, 1)], [0]))

#問1
score = [2] * 5; correct_answer = ["L", "M", "O", "N", "A"]
questions.append(Exam.MarkQuestion(sheets, "Q1", [[(0.05, 0.18), (0.48, 0.32)]], 26, score, correct_answer))
#問2
score = [2] * 8; correct_answer = ["A", "B", "F", "I", "O", "J", "M", "Q"]
questions.append(Exam.MarkQuestion(sheets, "Q2", [[(0.05, 0.32), (0.48, 0.53)]], 26, score, correct_answer))
#問3
score = [2] * 8; correct_answer = ["D", "M", "B", "N", "E", "O", "G", "L"]
questions.append(Exam.MarkQuestion(sheets, "Q3", [[(0.05, 0.53), (0.48, 0.75)]], 26, score, correct_answer))
#問4
score = [2] * 4; correct_answer = ["A", "B", "C", "B"]
questions.append(Exam.MarkQuestion(sheets, "Q4", [[(0.05, 0.75), (0.48, 0.90)]], 26, score, correct_answer))
#問5
score = [1] * 20; correct_answer = ["G", "B", "F", 
                                    "G", "B", "C", 
                                    "G", "D", "E",
                                    "G", "B", "J", "D",
                                    "H", "G", "B", "H",
                                    "G", "D", "I"]

questions.append(Exam.MarkQuestion(sheets, "Q5", [[(0.53, 0.08), (0.93, 0.54)]], 26, score, correct_answer))
#問6
score = [2] * 5; correct_answer = ["A", "B", "A", "A", "B"]
questions.append(Exam.MarkQuestion(sheets, "Q6", [[(0.53, 0.54), (0.93, 0.67)]], 26, score, correct_answer))
#問7
score = [2] * 5; correct_answer = ["D", "B", "G", "C", "A"]
questions.append(Exam.MarkQuestion(sheets, "Q7", [[(0.53, 0.67), (0.93, 0.80)]], 26, score, correct_answer))
#問8
score = [2] * 5; correct_answer = ["E", "A", "F", "B", "Z"]
questions.append(Exam.MarkQuestion(sheets, "Q8", [[(0.53, 0.80), (0.93, 0.94)]], 26, score, correct_answer))


マークの読み取りと採点

In [6]:
for i in range(1,8+1):
    questions[i].read()#; questions[i].get_correct_answer(); 
    questions[i].grading()
    pass


Q1 reading...
[11 12 14 13  0]
[1. 1. 1. 1. 1.]
[11 12 14 13  0]
[1. 1. 1. 1. 1.]
[11 12 14 13  0]
[1. 1. 1. 1. 1.]
Q2 reading...
[ 0  1  5  8 14  9 12 16]
[1. 1. 1. 1. 1. 1. 1. 1.]
down threshold to 0.18181818181818182
down threshold to 0.1652892561983471
down threshold to 0.15026296018031554
down threshold to 0.13660269107301412
down threshold to 0.124184264611831
down threshold to 0.11289478601075545
down threshold to 0.10263162364614131
down threshold to 0.09330147604194663
down threshold to 0.08481952367449694
down threshold to 0.0771086578859063
down threshold to 0.07009877989627845
down threshold to 0.06372616354207132
down threshold to 0.05793287594733756
[ 0  1  5  8 14  9 12 16]
[1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  5  8 14  9 12 16]
[1. 1. 1. 1. 1. 1. 1. 1.]
Q3 reading...
[ 3 12  1 13  4 14  6 11]
[1. 1. 1. 1. 1. 1. 1. 1.]
[ 3 12  1 13  4 14  6 11]
[1. 1. 1. 1. 1. 1. 1. 1.]
[ 3 12  1 13  4 14  6 11]
[1. 1. 1. 1. 1. 1. 1. 1.]
Q4 reading...
[0 1 2 1]
[1. 1. 1. 1.]
[0 1 2 1]
[1. 1.

In [9]:
for i in range(1,len(questions)):
    questions[i].update()
    pass

Q1 updating...
Folder is not exist...
Q2 updating...
Q3 updating...
Q4 updating...
Q5 updating...
Q6 updating...
Q7 updating...
Q8 updating...


In [14]:
#総合点の計算
totalscore = np.array([0] * len(sheets), dtype='float64')
for i in range(1, len(questions)):
    questions[i].scoring(BasePath)
    #print(questions[i].sumscore)
    totalscore += np.array(questions[i].sumscore, dtype='float64')
ave = np.average(totalscore)
med = np.median(totalscore)
std = np.std(totalscore)

print(totalscore)

#順位の計算
totalscore = pd.DataFrame({"score":totalscore}, index= questions[1].grade.columns)
rank = totalscore.rank(ascending=False, method='min')

#採点結果を保存
data = np.zeros((len(totalscore)))
columns = range(1)
rows = map(str, questions[1].grade.columns)
result = totalscore
path = f"{BasePath}/result"
result.to_csv(f"{path}.csv")

#書き込み
for i, sheet in enumerate(sheets):
    note = f"average:{int(ave)}, median:{int(med)}, std:{int(std)} rank:{int(rank.values[i])}/{len(sheets)}" 
    sheet.update_score_MD(totalscore.values[i], note)

[64. 86. 85.]


C:\Users\Yusaku\AppData\Local\Temp\ipykernel_31504\2292167151.py:27: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  note = f"average:{int(ave)}, median:{int(med)}, std:{int(std)} rank:{int(rank.values[i])}/{len(sheets)}"
